### ISSUE TITLE
S. Это будет наш секрет (решение задачи не принимает Yandex Handbook

### ISSUE THREAD

**Issue by Altair788** [Pavellver/Yandex_handbook_answers#42]
Благодарю вас за публикацию ваших решений. Я их разбираю, так как не все понятно. В процессе решения задачи S из блока 3.5 столкнулся с тем, что ваше решение не проходит.

**Comment by Pavellver** [comment]
Большое спасибо за отзыв, я выложил решения, поскольку. когда сам проходил, не с чем было свериться - это затрудняло процесс изучения. В задаче S из блока 3.5 мешали отступы между блоками программы - я их убрал и без них все должно работать.

**Comment by Altair788** [comment]
Спасибо за быстрый ответ. Не думал, что так скоро ответите. Решил таким образом:
shift = int(input())
alphabet = "abcdefghijklmnopqrstuvwxyz"
with open("public.txt", "r", encoding="UTF-8") as file_in:
    data = file_in.read()
    
    def encrypt_char(char):
        if char.lower() not in alphabet:
            return char
        
        is_upper = char.isupper()
        char_lower = char.lower()
        index = alphabet.index(char_lower)
        new_index = (index + shift) % len(alphabet)
        encrypted_char = alphabet[new_index]
        return encrypted_char.upper() if is_upper else encrypted_char
    
    encrypted_data = ''.join([encrypt_char(char) for char in data])
with open("private.txt", "w") as file_out:
    file_out.write(encrypted_data)
