### ISSUE TITLE
G. В эфире рубрика «Эксперименты»

### ISSUE THREAD

**Issue by Altair788** [Pavellver/Yandex_handbook_answers#44]
G. В эфире рубрика «Эксперименты»
Еще раз доброго времени, Павел. 
Вопрос по коду № 1: 
в строке:
def get_average():
    return round(2 * get_sum()[0] / len(numbers), 2), round(2 * get_sum()[1] / len(numbers), 2)
вопрос: зачем умножать на 2?

Вопрос по коду №2:
в конце кода снова прописывается numbers = tuple(). Зачем? Чтобы очистить значения, хранящиеся в кортеже?

Вопрос 3:
вам  было бы интересно взять на работу новичка? Готов за опыт работать. Я изучаю Python. Хотел бы работать среди опытных специалистов. Уволился в начале лета, чтобы полностью посвятить себя разработке и интересным проектам. 

numbers = tuple()

def enter_results(*args):
    global numbers
    numbers += args

def get_sum():
    return round(sum(numbers[::2]), 2), round(sum(numbers[1::2]), 2)

def get_average():
    return round(2 * get_sum()[0] / len(numbers), 2), round(2 * get_sum()[1] / len(numbers), 2)

numbers = tuple()

**Comment by Pavellver** [comment]
Здравствуйте, Эдуард.
Ответ № 1. Мы умножаем на 2 для получения правильного ответа, поскольку в функции get_sum() мы в первом и втором аргументах берём четные и нечетные индексы соответственно, а их как раз вдвое меньше, чем len(numbers) (длина переданного кортежа чисел). На мой взгляд у яндекса очень плохо сформулировано, что именно нужно сделать в задании, это пришлось додумывать самому.
Ответ № 2. В моем решении нет повторной строчки numbers = tuple(). Второй раз она ни к чему.
Ответ № 3. Я сам новичок в программировании, опытным специалистом пока не являюсь, тоже хотелось бы найти работу.
