### ISSUE TITLE
Опечатка в задании I. Очередь

### ISSUE THREAD

**Issue by Altair788** [Pavellver/Yandex_handbook_answers#45]
Привет. Нашел опечатку: 3 строка 
class Queue(list):
    def __init__(self):
        self.a = [] #  вот здесь отсутствует 'self'
...

🤝

**Comment by Altair788** [comment]
также еще один момент: прописывать list в class Queue не обязательно как мне кажется. Код работает и без list
✌️

**Comment by Altair788** [comment]
# задача J. Stack
class Stack:
    def __init__(self):
        self.a = []

    def push(self, item):
        return self.a.append(item)

    def pop(self):
        return self.a.pop()

    def is_empty(self):
        return self.a == []

**Comment by Pavellver** [comment]
Да, верно, там по условию задания вообще нужно писать класс без инициализатора. И наследование не нужно. Большое спасибо, исправлю.
