### ISSUE TITLE
Ошибка в D контроль параметров

### ISSUE THREAD

**Issue by Altair788** [Pavellver/Yandex_handbook_answers#47]
stdout:
/bin/sh ./build.sh 1>&2

stderr:
solution.py:2:8: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`
Код не соответствует стандарту PEP8
или в нем есть синтаксические ошибки
make: *** [Makefile:2: build] Error 1

Предлагаю решение:
def only_positive_even_sum(x, y):
    if isinstance(x, int) and isinstance(y, int):
        if (x > 0 and x % 2 == 0) and (y > 0 and y % 2 == 0):
            return x + y
        raise ValueError('Вызвано исключение ValueError')
    raise TypeError('Вызвано исключение TypeError')

**Comment by Pavellver** [comment]
Спасибо большое, раньше у меня решение проходило, но типы действительно нужно проверять через isinstance. Поправил.

**Comment by Altair788** [comment]
> Спасибо большое, раньше у меня решение проходило, но типы действительно нужно проверять через isinstance. Поправил.

Там еще вывод ожидается в таком формате: Вызвано исключение TypeError

**Comment by Pavellver** [comment]
Угу, именно такой вывод у меня и происходит.
![image](https://github.com/Pavellver/Yandex_handbook_answers/assets/124912104/167d09a8-1fc5-4b71-9a21-6a1d9591d772)
