### ISSUE TITLE
H. Валидация имени пользователя (в последнем тесте решение не проходит)

### ISSUE THREAD

**Issue by Altair788** [Pavellver/Yandex_handbook_answers#49]
Привет!
По-разному пробовал ее решить и с помощью ИИ, но в последнем тесте решение не проходит.

**Comment by Pavellver** [comment]
Спасибо, проблема оказалась действительно интересной. Полгода назад в задачах H и I тестов было 22 и программа их проходила, но сейчас, когда прибавили 23-й тест, то условий для успешного прохождения оказалось недостаточно. Опытным путем я установил, что в новом тесте, по всей видимости, в строке появляются кириллические символы (русские буквы), поэтому решение становится более "топорным" с перечислением только доступных символов в одной строке в обеих заданиях: `i.lower() not in '0123456789_abcdefghijklmnopqrstuvwxyz'`. Сами решения подправил.
